import os

class DbConfiguration:
    AUTHORIZATION_DB_HOST = os.getenv("AUTHORIZATION_DB_HOST")
    AUTHORIZATION_DB_PORT = os.getenv("AUTHORIZATION_DB_PORT")
    AUTHORIZATION_DB_DATABASE = os.getenv("AUTHORIZATION_DB_DATABASE")
    AUTHORIZATION_DB_USERNAME = os.getenv("AUTHORIZATION_DB_USERNAME")
    AUTHORIZATION_DB_PASSWORD = os.getenv("AUTHORIZATION_DB_PASSWORD")